name: docker build

on:
  push:
    branches: [ "test" ]

jobs:
 docker:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        docker: [20.10.21]

    steps:
    - name: build the docker image
    - uses: docker/build-action@v2
    - name: Set up docker${{ matrix.docker-version }}
    - uses: actions/setup-docker@v3
      with:
        docker-version: ${{ matrix.docker-version }}
        
    - name: build the docker image
      run: |
         docker build -t myapp .
         
    - name: build the container 
      run: |
          docker run --name yout -p 80:80b -d -it myapp2 
       
